<?php
/**
 * @file
 * This module is used to apply Omniture tracking codes to all HTML5 video.
 */

 /**
  * Impliments hook_preprocess_page().
  */
 function HTML5_video_tracking_preprocess_page () {
  // Include the protocol independant tracking codes needed by Collegeboard.
  // "/" not "//" because drupal adds "/" thinking we are site relative.
  // We exploit this here.
  drupal_add_js('/common.collegeboard.org/webanalytics/js/web_analytics_header.js');
  drupal_add_js(drupal_get_path('module','HTML5_video_tracking') . '/js/HTML5_video_tracking.js');
  drupal_add_js('/common.collegeboard.org/webanalytics/js/web_analytics_footer.js');
 }